export const GET_ALL_CLIENTS_REQUEST = 'GET_ALL_CLIENTS_REQUEST';
export const GET_ALL_CLIENTS_SUCCESS = 'GET_ALL_CLIENTS_SUCCESS';
export const GET_ALL_CLIENTS_FAILURE = 'GET_ALL_CLIENTS_FAILURE';

export const GET_USERS_PROJECTS_REQUEST = 'GET_USERS_PROJECTS_REQUEST';
export const GET_USERS_PROJECTS_SUCCESS = 'GET_USERS_PROJECTS_SUCCESS';
export const GET_USERS_PROJECTS_FAILURE = 'GET_USERS_PROJECTS_FAILURE';
