// creating client
export const CREATE_CLIENT_LOADING = "CREATE_CLIENT_LOADING";
export const CREATE_CLIENT_SUCCESS = "CREATE_CLIENT_SUCCESS";
export const CREATE_CLIENT_ERROR = "CREATE_CLIENT_ERROR";

// get client
export const GET_CLIENT_LOADING = "GET_CLIENT_LOADING";
export const GET_CLIENT_SUCCESS = "GET_CLIENT_SUCCESS";
export const GET_CLIENT_ERROR = "GET_CLIENT_ERROR";