//All Projects action types
export const SET_ALL_PROJECTS = "SET_ALL_PROJECTS";
export const SET_PROJECTS_LOADING = "SET_PROJECTS_LOADING";
export const SET_PROJECTS_ERROR = "SET_PROJECTS_ERROR";

export const CREATE_ALL_PROJECTS = "SET_ALL_PROJECTS";
export const CREATE_PROJECTS_LOADING = "SET_PROJECTS_LOADING";
export const CREATE_PROJECTS_ERROR = "SET_PROJECTS_ERROR";
//Tasks action types
export const SET_TASKS_OF_PROJECT = "SET_TASKS_OF_PROJECT";
