// getting Timers info

export const TIMERREQUEST = "TIMERREQUEST";
export const TIMERSUCCESS = "TIMERSUCCESS";
export const TIMERFAILURE = "TIMERFAILURE";

//getting TimeSheets info
export const TIMESHEETREQUEST = "TIMESHEETREQUEST";
export const TIMESHEETSUCCESS = "TIMESHEETSUCCESS";
export const TIMESHEETFAILURE = "TIMESHEETFAILURE";

// add members in team
export const ADDMEMBERREQUEST = "ADDMEMBERREQUEST";
export const ADDMEMBERSUCCESS = "ADDMEMBERSUCCESS";
export const ADDMEMBERFAILURE = "ADDMEMBERFAILURE";

//delete members in team
export const DELETEMEMBERREQUEST = "DELETEMEMBERREQUEST";
export const DELETEMEMBERSUCCESS = "DELETEMEMBERSUCCESS";
export const DELETEMEMBERFAILURE = "DELETEMEMBERFAILURE";
