//All Projects action types
export const SET_ALL_SECTION = "SET_ALL_SECTION";
export const SET_SECTION_LOADING = "SET_SECTION_LOADING";
export const SET_SECTION_ERROR = "SET_SECTION_ERROR";

export const SET_TASKS_OF_PROJECT = "SET_TASKS_OF_PROJECT";

export const SET_ALL_SPEC_PROJECT = "SET_ALL_SPEC_PROJECT";
export const SET_SPEC_PROJECT_LOADING = "SET_SPEC_PROJECT_LOADING";
export const SET_SPEC_PROJECT_ERROR = "SET_SPEC_PROJECT_ERROR";

export const CREATE_SECTION = "CREATE_SECTION";
export const CREATE_SECTION_LOADING = "CREATE_SECTION_LOADING";
export const CREATE_SECTION_ERROR = "CREATE_SECTION_ERROR";