export const SET_CURRENT_PROJECT = "SET_CURRENT_PROJECT";
export const SET_CURRENT_TASK = "SET_CURRENT_TASK";

export const SET_TIMER_ACTIVE = "SET_TIMER_ACTIVE";
export const SET_TIMER_STOPPED = "SET_TIMER_STOPPED";
