export const SET_CURRENT_PROJECT = "SET_CURRENT_PROJECT";
export const SET_CURRENT_TASK = "SET_CURRENT_TASK";

export const START_TIMER = "START_TIMER";
export const STOP_TIMER = "STOP_TIMER";

export const SET_TIMER_STATUS = "SET_TIMER_STATUS";

export const SET_COMMENT = "SET_COMMENT";
export const SET_COUNTER = "SET_COUNTER";

export const SET_INTERVAL = "SET_INTERVAL";
